WebApplication3/Controllers/BeslenmePlanıController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Areas.Identity.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class BeslenmePlanıController : Controller
    {
        private readonly FitnessDB _context;
        private readonly UserManager<AppUser> _userManager;

        public BeslenmePlanıController(FitnessDB context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BeslenmePlanı
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (await _userManager.IsInRoleAsync(user, "Danışman"))
            {
                var danismanid = _userManager.GetUserId(User);

                var danismanmusterileri = _context.DanismanMusteriAtamas.Where(c => c.DanismanID == danismanid).ToList();



                var filtered = _context.BeslenmePlan.Where(a => danismanmusterileri.Select(d => d.MusteriID).Contains(a.MusteriID)).ToList();

                return View(filtered);

            }
            else if(await  _userManager.IsInRoleAsync(user,"Admin"))
            {
                var adminid = _userManager.GetUserId(User);

                return _context.BeslenmePlan != null ?
                    View(await _context.BeslenmePlan.ToListAsync()) :
                    Problem("Entity set 'FitnessDB.MusteriProgresses'  is null.");


            }
            var userid = _userManager.GetUserId(User);
            return _context.BeslenmePlan != null ?
                          View(await _context.BeslenmePlan.Where(a => a.MusteriID == userid).ToListAsync()) :
                          Problem("Entity set 'FitnessDB.AntrenmanProgramlarıs'  is null.");
        }

        // GET: BeslenmePlanı/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BeslenmePlanı == null)
            {
                return NotFound();
            }

            var beslenmePlanı = await _context.BeslenmePlanı
                .FirstOrDefaultAsync(m => m.Id == id);
            if (beslenmePlanı == null)
            {
                return NotFound();
            }

            return View(beslenmePlanı);
        }

        // GET: BeslenmePlanı/Create
        [Authorize(Roles = "Danışman")]
        public IActionResult Create()
        {
            var danismanid = _userManager.GetUserId(User);
            var danismanmusterileri = _context.DanismanMusteriAtamas.Where(c => c.DanismanID == danismanid).Select(c => c.MusteriID)
                .ToList();
            ViewBag.userid = danismanid;
            ViewBag.Musteriler = new SelectList(danismanmusterileri, "MusteriID");
            return View();
        }

        // POST: BeslenmePlanı/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Danışman")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,MusteriID,Hedef,GunlukBesin,KaloriHedefi")] BeslenmePlanı beslenmePlanı)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                beslenmePlanı.UserId = userId;
                _context.Add(beslenmePlanı);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(beslenmePlanı);
        }

        // GET: BeslenmePlanı/Edit/5
        [Authorize(Roles = "Danışman,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BeslenmePlanı == null)
            {
                return NotFound();
            }

            var beslenmePlanı = await _context.BeslenmePlanı.FindAsync(id);
            if (beslenmePlanı == null)
            {
                return NotFound();
            }
            return View(beslenmePlanı);
        }

        // POST: BeslenmePlanı/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Danışman,Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,MusteriID,Hedef,GunlukBesin,KaloriHedefi")] BeslenmePlanı beslenmePlanı)
        {
            if (id != beslenmePlanı.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beslenmePlanı);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeslenmePlanıExists(beslenmePlanı.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(beslenmePlanı);
        }

        // GET: BeslenmePlanı/Delete/5
        [Authorize(Roles = "Danışman,Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BeslenmePlanı == null)
            {
                return NotFound();
            }

            var beslenmePlanı = await _context.BeslenmePlanı
                .FirstOrDefaultAsync(m => m.Id == id);
            if (beslenmePlanı == null)
            {
                return NotFound();
            }

            return View(beslenmePlanı);
        }

        // POST: BeslenmePlanı/Delete/5
        [Authorize(Roles = "Danışman,Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BeslenmePlanı == null)
            {
                return Problem("Entity set 'FitnessDB.BeslenmePlanı'  is null.");
            }
            var beslenmePlanı = await _context.BeslenmePlanı.FindAsync(id);
            if (beslenmePlanı != null)
            {
                _context.BeslenmePlanı.Remove(beslenmePlanı);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BeslenmePlanıExists(int id)
        {
          return (_context.BeslenmePlanı?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication3/Controllers/DanismanMusteriAtamaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WebApplication3.Areas.Identity.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    [Authorize(Roles ="Admin")]
    public class DanismanMusteriAtamaController : Controller
    {
        private readonly FitnessDB _coontext;

        public DanismanMusteriAtamaController(FitnessDB context)
        {
        _coontext = context;
        }


        public IActionResult Index()
        {
            var danisman = _coontext.Users.Where(u => u.Rol == "Danışman");
            var musteri = _coontext.Users.Where(u => u.Rol == "Müşteri");

            
            ViewBag.danisman = danisman;
            ViewBag.musteri = musteri;


            return View();
        }



        [HttpPost]
        public IActionResult Atama(string danismanID,  string musteriID, string musteriAdi)
        {
            var atama = new DanismanMusteriAtama
            {
                DanismanID = danismanID,
                MusteriID = musteriID,
                
            };

            _coontext.DanismanMusteriAtamas.Add( atama );
            _coontext.SaveChanges();

            return RedirectToAction("Index");


        }

    }
}

WebApplication3/Controllers/MesajlarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Areas.Identity.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class MesajlarsController : Controller
    {
        private readonly FitnessDB _context;
        private readonly UserManager<AppUser> _userManager; 

        public MesajlarsController(FitnessDB context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Mesajlars
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (await _userManager.IsInRoleAsync(user,"Müşteri"))
            {
                var userid = _userManager.GetUserId(User);
                return _context.Mesajlar != null ?
                              View(await _context.Mesajlar.Where(a => a.GönderenID == userid || a.AlıcıID == userid).ToListAsync()) :
                              Problem("Entity set 'FitnessDB.AntrenmanProgramlarıs'  is null.");
            }

            else if(await _userManager.IsInRoleAsync(user,"Danışman"))
            {
                var userid = _userManager.GetUserId(User);
                return _context.Mesajlar != null ?
                              View(await _context.Mesajlar.Where(a => a.GönderenID == userid || a.AlıcıID == userid).ToListAsync()) :
                              Problem("Entity set 'FitnessDB.AntrenmanProgramlarıs'  is null.");
            }

              return _context.Mesajlar != null ? 
                          View(await _context.Mesajlar.ToListAsync()) :
                          Problem("Entity set 'FitnessDB.Mesajlar'  is null.");
        }

        // GET: Mesajlars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Mesajlar == null)
            {
                return NotFound();
            }

            var mesajlar = await _context.Mesajlar
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mesajlar == null)
            {
                return NotFound();
            }

            return View(mesajlar);
        }

        // GET: Mesajlars/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            if (await _userManager.IsInRoleAsync(user, "Danışman"))
            {
                var danismanid = _userManager.GetUserId(User);
                var danismanmusterileri = _context.DanismanMusteriAtamas.Where(c => c.DanismanID == danismanid).Select(c => c.MusteriID)
                    .ToList();
                
                var danismanmusteri = _context.Users.Where(u=>danismanmusterileri.Contains(u.Id)).Select(u=> new {u.Id, u.Firstname}).ToList();
                var atama = _context.DanismanMusteriAtamas.FirstOrDefault(a => a.DanismanID == danismanid);
                var name = atama.Danisman.Firstname;
                
                //var name = _context.Users.FirstOrDefault(a => a.Id == danismanid);
                
                ViewBag.Seçenekler = new SelectList(danismanmusterileri,"");
                ViewBag.Name = name;
                ViewBag.id = danismanid;
                
            }
            else if(await _userManager.IsInRoleAsync(user,"Müşteri"))
            {
                var musteriid = _userManager.GetUserId(User);
                var danismanmusterileri = _context.DanismanMusteriAtamas.Where(c => c.MusteriID == musteriid).Select(c => c.DanismanID)
                    .ToList();
                var atama = _context.DanismanMusteriAtamas.FirstOrDefault(a=>a.MusteriID==musteriid);
                var name = atama.Musteri.Firstname;
                ViewBag.Seçenekler = new SelectList(danismanmusterileri, "DanismanID");
                ViewBag.Name = name;
                ViewBag.id = musteriid;
            }

            return View();
        }

        // POST: Mesajlars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AlıcıID,AlıcıName,GönderenID,GönderenName,Mesajİcerigi")] Mesajlar mesajlar)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                mesajlar.GönderenID = userId;
                _context.Add(mesajlar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mesajlar);
        }

        // GET: Mesajlars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Mesajlar == null)
            {
                return NotFound();
            }

            var mesajlar = await _context.Mesajlar.FindAsync(id);
            if (mesajlar == null)
            {
                return NotFound();
            }
            return View(mesajlar);
        }

        // POST: Mesajlars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AlıcıID,AlıcıName,GönderenID,GönderenName,Mesajİcerigi")] Mesajlar mesajlar)
        {
            if (id != mesajlar.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mesajlar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MesajlarExists(mesajlar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mesajlar);
        }

        // GET: Mesajlars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Mesajlar == null)
            {
                return NotFound();
            }

            var mesajlar = await _context.Mesajlar
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mesajlar == null)
            {
                return NotFound();
            }

            return View(mesajlar);
        }

        // POST: Mesajlars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Mesajlar == null)
            {
                return Problem("Entity set 'FitnessDB.Mesajlar'  is null.");
            }
            var mesajlar = await _context.Mesajlar.FindAsync(id);
            if (mesajlar != null)
            {
                _context.Mesajlar.Remove(mesajlar);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MesajlarExists(int id)
        {
          return (_context.Mesajlar?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication3/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication3.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleController(RoleManager<IdentityRole> roleManager) 
        {
        
        _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }
        [HttpGet]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if(!_roleManager.RoleExistsAsync(role.Name).GetAwaiter().GetResult()) 
            {
            _roleManager.CreateAsync(new IdentityRole(role.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
   @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
   <link rel="stylesheet" href="~/css/mytheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitLife</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.IsInRole("Admin")){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MusteriProgresses" asp-action="Index">İlerlemem</a>
                        </li>
                        @if(User.IsInRole("Admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanismanMusteriAtama" asp-action="Index">Atama Yap</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AntrenmanProgramları" asp-action="Index">Antrenman Programları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BeslenmePlanı" asp-action="Index">Beslenme Planı</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanismanBilgileris" asp-action="Index">Danışman Bilgileri</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mesajlars" asp-action="Index">Mesaj Kutusu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kullanıcılar" asp-action="Index">Kullanıcılar</a>
                        </li>



                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>